# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Kiwix.KiwixJS.Electron
PackageVersion: 3.7.1-E
InstallerLocale: en-GB
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/kiwix/kiwix-js-pwa/releases/download/v3.7.1/Kiwix-JS-Electron-Win7-Setup-3.7.1-E.exe
  InstallerSha256: 2D45E14FBD569C5605688A3D053A48247BE273D11D65B3C89C544B6513748616
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/kiwix/kiwix-js-pwa/releases/download/v3.7.1/Kiwix-JS-Electron-Win7-Setup-3.7.1-E.exe
  InstallerSha256: 2D45E14FBD569C5605688A3D053A48247BE273D11D65B3C89C544B6513748616
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-08-07
